language: python

sudo: false

python:
  - 3.4
  - 3.3

install:
  - pip install werkzeug multipart coverage coveralls anillo itsdangerous pytest

script:
  - coverage run --source=anillo_auth -m py.test -v --tb=native

after_success:
  - coveralls
